function txt = generateMethods(cmp, varargin)
% hwalker.experiment.generateMethods  Auto-generate paper Methods text from a comparison.
%
%   txt = hwalker.experiment.generateMethods(cmp)
%   txt = hwalker.experiment.generateMethods(cmp, 'OutFile', 'methods.md')
%
% Produces paper-ready Methods section (Markdown) describing:
%   - data acquisition (modalities present)
%   - signal processing (cutoffs, MVC, etc.)
%   - statistical analysis (tests used + corrections)
%   - effect sizes reported
%
% Returns the text. If 'OutFile' given, also writes to disk.

    p = inputParser;
    addParameter(p, 'OutFile', '');
    parse(p, varargin{:});

    L = {};
    L{end+1} = '## Methods (auto-generated by hwalker.experiment.generateMethods)';
    L{end+1} = '';

    % Codex pass 10 fix: detect which modalities are actually present from
    % cmp's feature names — generate text only for those.
    metricNames = fieldnames(cmp);
    has = struct();
    has.robot     = any(contains(metricNames, {'stride_time','cadence','stride_length','force_rmse','force_mae','stance_pct','swing_pct'}));
    has.motion    = any(contains(metricNames, {'knee_','hip_','ankle_'}));
    has.grf       = any(contains(metricNames, {'grf_','COP_'}));
    has.emg       = any(contains(metricNames, 'emg_'));
    has.loadcell  = any(contains(metricNames, 'bws_'));

    nMod = sum([has.robot has.motion has.grf has.emg has.loadcell]);
    L{end+1} = '### Data Acquisition';
    L{end+1} = sprintf('%d time-synchronized modality stream(s) were recorded:', nMod);
    if has.robot
        L{end+1} = '- **Robot data** (H-Walker firmware): cable tension and position sampled at the firmware''s native rate; sync TTL recorded on a dedicated channel.';
    end
    if has.motion
        L{end+1} = '- **Motion capture**: 3D marker trajectories.';
    end
    if has.grf
        L{end+1} = '- **Ground reaction force**: instrumented treadmill or stand-alone force plates.';
    end
    if has.emg
        L{end+1} = '- **EMG** (multi-channel surface): bilateral lower-limb muscles.';
    end
    if has.loadcell
        L{end+1} = '- **Body-weight-support loadcell**: continuous BWS force.';
    end
    L{end+1} = '';
    L{end+1} = '### Signal Processing';
    if has.motion
        L{end+1} = '- Marker trajectories were low-pass filtered at 6 Hz (Butterworth, 4th order, zero-phase via filtfilt).';
    end
    if has.grf
        L{end+1} = '- Ground reaction forces were low-pass filtered at 20 Hz.';
        L{end+1} = '- Heel-strike and toe-off events were detected from vertical GRF using a 30 N threshold (Winter 2009).';
    end
    if has.emg
        L{end+1} = '- EMG was DC-removed, bandpass filtered (20-450 Hz, 4th order Butterworth, zero-phase), full-wave rectified, and RMS-windowed (50 ms). When MVC trials were available, signals were normalized to peak MVC envelope (% MVC).';
    end
    if has.loadcell
        L{end+1} = '- The body-weight-support loadcell was tare-zeroed against the first second of each trial and low-pass filtered at 10 Hz.';
    end
    if has.robot && ~has.grf
        L{end+1} = '- In the absence of force-plate data, heel-strike events were taken from H-Walker GCP rising edges.';
    end
    L{end+1} = '';

    L{end+1} = '### Statistical Analysis';
    metrics = fieldnames(cmp);
    K = NaN;
    if ~isempty(metrics)
        K = numel(cmp.(metrics{1}).condition_names);
    end
    L{end+1} = sprintf('A total of %d metrics were extracted across %d conditions: %s.', ...
        numel(metrics), K, ...
        strjoin(cmp.(metrics{1}).condition_names, ', '));
    L{end+1} = 'Test selection followed `hwalker.stats.decisionTree`, which screens for normality (Lilliefors) and homogeneity of variance (Brown-Forsythe Levene) and recommends the appropriate parametric or non-parametric test.';
    if ~isempty(metrics)
        L{end+1} = sprintf('For each metric, %s was used.', cmp.(metrics{1}).recommended_test);
    end
    L{end+1} = 'For ANOVA-class tests with three or more conditions, post-hoc pairwise comparisons used Tukey HSD (exploratory) or Holm-Bonferroni (planned), as documented per metric.';
    L{end+1} = 'Sphericity was assessed via Mauchly''s test; Greenhouse-Geisser correction was applied when ε < 0.75, otherwise Huynh-Feldt.';
    L{end+1} = 'Effect sizes were reported as Cohen''s d_av (Cumming 2012) for paired comparisons, partial η² (Olejnik & Algina 2003) for repeated-measures ANOVA, and ω² (Lakens 2013) for one-way ANOVA.';
    L{end+1} = 'Significance threshold was α = 0.05.';
    L{end+1} = '';

    L{end+1} = '### Per-Metric Summary';
    L{end+1} = '| Metric | Test | F or t | p | effect size |';
    L{end+1} = '|---|---|---|---|---|';
    for i = 1:numel(metrics)
        nm = metrics{i};
        c = cmp.(nm);
        ts = c.test_struct;
        if isstruct(ts)
            if isfield(ts, 'F') && ~isnan(ts.F)
                stat = sprintf('F=%.2f', ts.F);
            elseif isfield(ts, 't_stat')
                stat = sprintf('t=%.2f', ts.t_stat);
            elseif isfield(ts, 't')
                stat = sprintf('t=%.2f', ts.t);
            else
                stat = '—';
            end
            if isfield(ts, 'recommended_p') && ~isnan(ts.recommended_p)
                pv = sprintf('%.4f', ts.recommended_p);
            elseif isfield(ts, 'p_ttest')
                pv = sprintf('%.4f', ts.p_ttest);
            elseif isfield(ts, 'p')
                pv = sprintf('%.4f', ts.p);
            else
                pv = '—';
            end
            es = '';
            if ~isnan(c.effect_size), es = sprintf('%.3f', c.effect_size); end
            L{end+1} = sprintf('| %s | %s | %s | %s | %s |', ...
                nm, c.recommended_test, stat, pv, es);                    %#ok<AGROW>
        end
    end
    L{end+1} = '';

    L{end+1} = '### Reproducibility';
    L{end+1} = 'Source code, journal preset specifications, and the full result struct were saved as a reproducibility package (`hwalker.meta.reproPackage`).';
    L{end+1} = 'Each package contains: (i) result.mat / result.json with all per-stride values, (ii) input CSV SHA-256 hashes, (iii) MATLAB version and active toolbox list, (iv) git commit hash of the analysis code.';
    L{end+1} = '';

    txt = strjoin(L, sprintf('\n'));

    if ~isempty(p.Results.OutFile)
        fid = fopen(p.Results.OutFile, 'w');
        if fid > 0
            fwrite(fid, txt, 'char');
            fclose(fid);
            fprintf('[generateMethods] Wrote: %s\n', p.Results.OutFile);
        end
    end
end
