function p = journalPreset(name, varargin)
% hwalker.plot.journalPreset  Return journal figure specification struct.
%
%   p = hwalker.plot.journalPreset('IEEE')        % general IEEE Trans
%   p = hwalker.plot.journalPreset('TRO')         % IEEE Transactions on Robotics
%   p = hwalker.plot.journalPreset('RAL')         % IEEE RA-L
%   p = hwalker.plot.journalPreset('TNSRE')       % IEEE Trans on Neural Sys & Rehab Eng
%   p = hwalker.plot.journalPreset('TMECH')       % IEEE Trans on Mechatronics
%   p = hwalker.plot.journalPreset('ICRA')        % ICRA / IROS conference
%   p = hwalker.plot.journalPreset('IROS')        % alias for ICRA
%   p = hwalker.plot.journalPreset('IJRR')        % Int J Robotics Research (SAGE)
%   p = hwalker.plot.journalPreset('SciRobotics') % Science Robotics (AAAS)
%   p = hwalker.plot.journalPreset('SoftRobotics')% Soft Robotics (Liebert)
%   p = hwalker.plot.journalPreset('FrontNeurorobot') % Frontiers in Neurorobotics
%   p = hwalker.plot.journalPreset('AuRo')        % Autonomous Robots (Springer)
%   p = hwalker.plot.journalPreset('Nature')      % general Nature
%   % Plus the original 6: 'IEEE','Nature','APA','Elsevier','MDPI','JNER'
%
% Custom preset (your journal not in the list?):
%   p = hwalker.plot.journalPreset('Custom', struct( ...
%         'name','MyJournal','col1mm',88, 'col2mm',180, ...
%         'col1h_mm',65,'col2h_mm',90, ...
%         'font','Arial','bodyPt',8,'strokePt',0.75, ...
%         'dpi',300,'paletteName','wong'));
%
% Use `hwalker.plot.listJournals` to print all available presets.
%
% Verified specs based on CLAUDE.md authoritative table.
%
% CHOOSING THE NUMBERS — current journal author guidelines specify RANGES
% (e.g., IEEE allows 7-10pt body; Elsevier accepts 300/500/1000 dpi). The
% values below are the LAB STANDARD: a single concrete choice within each
% allowed range, picked for legibility at print size. To use a different
% combination for one figure, copy the returned struct and override fields.
%
% Verified against (codex web-search 2026-05-04):
%   IEEE Author Center, Nature figure guide, APA 7 Purdue OWL,
%   Elsevier artwork sizing, MDPI layout/style, JNER submission guidelines.
% All values fall within currently published tolerances. Discrepancies of
% ±1 mm reflect rounding (e.g., IEEE 2col 7.16in = 181.864 mm → rounded 181).
%
% Returned struct fields:
%   name, full           string identifiers
%   col1mm, col1h_mm     1-column width / height (mm)
%   col2mm, col2h_mm     2-column width / height (mm)
%   col15mm, col15h_mm   1.5-column (Elsevier only) — NaN otherwise
%   maxHmm               maximum allowed figure height (page constraint)
%   col1in, col2in, col15in        same widths in inches (1 in = 25.4 mm)
%   col1h_in, col2h_in, col15h_in  same heights in inches
%   font, fontFallback   primary font + cellstr fallback chain
%   bodyPt, axisPt       body / axis tick label size (pt)
%   legendPt, titlePt    legend / title text size (pt)
%   strokePt             plotted line width (pt)
%   axesPt               axes spine line width (pt) — fixed across journals
%   gridPt               grid line width (pt)
%   palette              Nx3 RGB matrix used for line / marker colors
%   paletteName          'wong' | 'grayscale' | 'default' | 'elsevier'
%   colorblindSafe       logical flag
%   bg, axisColor, gridColor   hex strings
%   formats              cellstr of accepted export formats (informational)
%   dpi                  raster export DPI
%   interpreter          'tex' | 'latex' | 'none' — text interpreter for labels
%   notes                string for documentation

    % ---------- Color palettes ----------
    % Wong color-blind safe palette — Wong B (2011) Nature Methods 8:441
    wongColors = [
          0  114  178;   % blue
        230  159    0;   % orange
         86  180  233;   % sky blue
          0  158  115;   % bluish green
        240  228   66;   % yellow
        213   94    0;   % vermillion
        204  121  167    % reddish purple
    ] / 255;

    grayscaleColors = [
        0    0    0   ;
        0.40 0.40 0.40;
        0.65 0.65 0.65;
        0.20 0.20 0.20;
        0.50 0.50 0.50;
        0.75 0.75 0.75;
        0.15 0.15 0.15
    ];

    defaultColors = [
        0      0.447  0.741;
        0.850  0.325  0.098;
        0.929  0.694  0.125;
        0.494  0.184  0.556;
        0.466  0.674  0.188;
        0.301  0.745  0.933;
        0.635  0.078  0.184
    ];

    elsevierColors = [
        228   26   28;
         55  126  184;
         77  175   74;
        152   78  163;
        255  127    0;
        255  255   51;
        166   86   40
    ] / 255;

    % ---------- Preset table (LAB STANDARD values per journal guidelines) ----------
    presets.IEEE = makePreset( ...
        'IEEE', 'IEEE Transactions / Journals', ...
        88.9, 70.0,  181.0, 90.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'grayscale', false, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','TIFF','SVG','PNG'}, 600, 'tex', ...
        '1col 88.9mm / 2col 181mm · 8-10pt Times · grayscale preferred');

    presets.Nature = makePreset( ...
        'Nature', 'Nature · Nature journals', ...
        89.0, 60.0,  183.0, 90.0,  NaN, NaN,  247.0, ...
        'Helvetica', {'Helvetica','Arial','sans-serif'}, ...
        7, 7, 6, 8,   0.5, 0.6, 0.25, ...
        'wong', true, '#ffffff', '#000000', '#E5E5E5', ...
        {'PDF','EPS','AI','TIFF'}, 300, 'tex', ...
        'Single 89mm / double 183mm · Helvetica 5-7pt · Wong colorblind-safe');

    presets.APA = makePreset( ...
        'APA', 'APA 7th edition', ...
        85.0, 65.0,  174.0, 100.0, NaN, NaN,  235.0, ...
        'Arial', {'Arial','Helvetica','sans-serif'}, ...
        10, 10, 9, 11, 0.75, 0.6, 0.3, ...
        'grayscale', false, '#ffffff', '#000000', '#DDDDDD', ...
        {'PDF','SVG','PNG','TIFF'}, 300, 'tex', ...
        'Sans-serif 8-14pt · grayscale preferred · figure note below');

    presets.Elsevier = makePreset( ...
        'Elsevier', 'Elsevier journals', ...
        90.0, 60.0,  190.0, 90.0,  140.0, 80.0,  240.0, ...
        'Arial', {'Arial','Helvetica','sans-serif'}, ...
        8, 8, 7, 9,   0.5, 0.6, 0.25, ...
        'elsevier', false, '#ffffff', '#000000', '#DDDDDD', ...
        {'EPS','PDF','TIFF','JPEG'}, 300, 'tex', ...
        'Single 90mm / 1.5 col 140mm / double 190mm · Arial · EPS preferred');

    presets.MDPI = makePreset( ...
        'MDPI', 'MDPI (Applied Sciences, Sensors, etc.)', ...
        85.0, 65.0,  170.0, 90.0,  NaN, NaN,  225.0, ...
        'Palatino Linotype', {'Palatino Linotype','Palatino','Book Antiqua','serif'}, ...
        8, 8, 7, 10,  0.75, 0.6, 0.3, ...
        'default', false, '#ffffff', '#000000', '#E0E0E0', ...
        {'PDF','TIFF','PNG','EPS'}, 1000, 'tex', ...
        'Single 85mm / double 170mm · Palatino 8pt · 1000 dpi line art');

    presets.JNER = makePreset( ...
        'JNER', 'J. NeuroEngineering & Rehabilitation (BMC)', ...
        85.0, 65.0,  170.0, 90.0,  NaN, NaN,  225.0, ...
        'Arial', {'Arial','Helvetica','sans-serif'}, ...
        8, 8, 7, 10,  0.75, 0.6, 0.3, ...
        'wong', true, '#ffffff', '#000000', '#E0E0E0', ...
        {'PDF','EPS','PNG','TIFF'}, 300, 'tex', ...
        'Springer/BMC · Arial 8pt · colorblind-safe · 300 dpi');

    % ============================================================
    %  ROBOTICS-SPECIFIC PRESETS (added for H-Walker domain)
    % ============================================================

    %  IEEE Transactions on Robotics — flagship robotics journal.
    %  Same column widths as general IEEE Trans (88.9 / 181 mm).
    presets.TRO = makePreset( ...
        'TRO', 'IEEE Transactions on Robotics (T-RO)', ...
        88.9, 70.0,  181.0, 90.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'wong', true, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','TIFF','SVG','PNG'}, 600, 'tex', ...
        'IEEE T-RO · 1col 88.9mm / 2col 181mm · Times 8pt · 600dpi · colorblind-safe recommended');

    %  IEEE Robotics and Automation Letters — most active venue
    %  Standard IEEE conference template (2-col 7.16in = 178mm)
    presets.RAL = makePreset( ...
        'RAL', 'IEEE Robotics and Automation Letters (RA-L)', ...
        88.9, 65.0,  181.0, 80.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'wong', true, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','TIFF','PNG'}, 600, 'tex', ...
        'IEEE RA-L · accompanying ICRA/IROS · 1col 88.9mm / 2col 181mm · Times 8pt');

    %  IEEE Trans on Neural Systems and Rehabilitation Engineering
    %  Most-relevant journal for H-Walker (gait rehab robot) work
    presets.TNSRE = makePreset( ...
        'TNSRE', 'IEEE Trans on Neural Systems and Rehabilitation Engineering', ...
        88.9, 70.0,  181.0, 90.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'wong', true, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','TIFF','SVG','PNG'}, 600, 'tex', ...
        'IEEE TNSRE · rehabilitation engineering · 1col 88.9mm / 2col 181mm · 600dpi');

    %  IEEE Transactions on Mechatronics
    presets.TMECH = makePreset( ...
        'TMECH', 'IEEE/ASME Transactions on Mechatronics (T-MECH)', ...
        88.9, 70.0,  181.0, 90.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'default', false, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','TIFF','PNG'}, 600, 'tex', ...
        'IEEE/ASME T-MECH · 1col 88.9mm / 2col 181mm · Times 8pt · 600dpi');

    %  ICRA / IROS conference paper (same template)
    %  IEEE conference 2-column = 7.16 in = 181.86 mm; usually 6 pages
    presets.ICRA = makePreset( ...
        'ICRA', 'IEEE ICRA / IROS / Humanoids / RoboSoft conferences', ...
        88.9, 65.0,  181.0, 80.0,  NaN, NaN,  216.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        8, 8, 7, 10,  1.0, 0.6, 0.4, ...
        'wong', true, '#ffffff', '#000000', '#CCCCCC', ...
        {'PDF','EPS','PNG'}, 600, 'tex', ...
        'IEEE conference template · 1col 88.9mm / 2col 181mm · Times 8pt');
    presets.IROS = presets.ICRA;
    presets.IROS.name = 'IROS';
    presets.IROS.full = 'IEEE/RSJ IROS — uses ICRA template';

    %  International Journal of Robotics Research (SAGE)
    presets.IJRR = makePreset( ...
        'IJRR', 'International Journal of Robotics Research (SAGE)', ...
        86.0, 65.0,  178.0, 90.0,  NaN, NaN,  240.0, ...
        'Times', {'Times','Times New Roman','serif'}, ...
        9, 9, 8, 11,  0.75, 0.6, 0.3, ...
        'default', false, '#ffffff', '#000000', '#DDDDDD', ...
        {'PDF','EPS','TIFF'}, 300, 'tex', ...
        'SAGE IJRR · 1col 86mm / 2col 178mm · Times 9pt · 300 dpi');

    %  Science Robotics (AAAS)
    presets.SciRobotics = makePreset( ...
        'SciRobotics', 'Science Robotics (AAAS)', ...
        90.0, 65.0,  184.0, 95.0,  NaN, NaN,  235.0, ...
        'Helvetica', {'Helvetica','Arial','sans-serif'}, ...
        7, 7, 6, 9,   0.5, 0.6, 0.25, ...
        'wong', true, '#ffffff', '#000000', '#E5E5E5', ...
        {'PDF','EPS','AI','TIFF'}, 300, 'tex', ...
        'Science Robotics · 1col 90mm / 2col 184mm · Helvetica 5-7pt · CB-safe');

    %  Soft Robotics (Mary Ann Liebert)
    presets.SoftRobotics = makePreset( ...
        'SoftRobotics', 'Soft Robotics (Mary Ann Liebert)', ...
        84.0, 65.0,  174.0, 95.0,  NaN, NaN,  235.0, ...
        'Arial', {'Arial','Helvetica','sans-serif'}, ...
        9, 9, 8, 11,  0.75, 0.6, 0.3, ...
        'wong', true, '#ffffff', '#000000', '#DDDDDD', ...
        {'PDF','EPS','TIFF','PNG'}, 300, 'tex', ...
        'Soft Robotics · 1col 84mm / 2col 174mm · Arial 9pt · 300 dpi · CB-safe');

    %  Frontiers in Neurorobotics (Frontiers Media)
    presets.FrontNeurorobot = makePreset( ...
        'FrontNeurorobot', 'Frontiers in Neurorobotics', ...
        85.0, 65.0,  180.0, 90.0,  NaN, NaN,  240.0, ...
        'Arial', {'Arial','Helvetica','sans-serif'}, ...
        9, 9, 8, 11,  0.5, 0.6, 0.25, ...
        'wong', true, '#ffffff', '#000000', '#E0E0E0', ...
        {'PDF','EPS','TIFF','PNG'}, 300, 'tex', ...
        'Frontiers in Neurorobotics · 1col 85mm / 2col 180mm · Arial 9pt');

    %  Autonomous Robots (Springer Nature)
    presets.AuRo = makePreset( ...
        'AuRo', 'Autonomous Robots (Springer)', ...
        84.0, 65.0,  174.0, 90.0,  NaN, NaN,  234.0, ...
        'Times New Roman', {'Times New Roman','Times','serif'}, ...
        9, 9, 8, 11,  0.5, 0.6, 0.3, ...
        'default', false, '#ffffff', '#000000', '#DDDDDD', ...
        {'PDF','EPS','TIFF'}, 300, 'tex', ...
        'Springer Autonomous Robots · 1col 84mm / 2col 174mm · Times 9pt');

    % ---- Custom preset injection ----
    % Allow caller to register a one-off preset on the fly:
    %   p = hwalker.plot.journalPreset('Custom', struct(...))
    if strcmpi(name, 'Custom')
        if numel(varargin) < 1 || ~isstruct(varargin{1})
            error('hwalker:plot:customNeedsStruct', ...
                'Custom preset requires a struct: hwalker.plot.journalPreset(''Custom'', struct(...))');
        end
        p = mergeWithDefaults(varargin{1});
        p = postProcess(p, wongColors, grayscaleColors, defaultColors, elsevierColors);
        return
    end

    if ~isfield(presets, name)
        validNames = strjoin(fieldnames(presets), ', ');
        error('hwalker:plot:unknownJournal', ...
            'Unknown journal ''%s''. Valid: %s', name, validNames);
    end

    p = presets.(name);
    p = postProcess(p, wongColors, grayscaleColors, defaultColors, elsevierColors);
end


function p = postProcess(p, wongColors, grayscaleColors, defaultColors, elsevierColors)
    switch p.paletteName
        case 'wong',      p.palette = wongColors;
        case 'grayscale', p.palette = grayscaleColors;
        case 'elsevier',  p.palette = elsevierColors;
        otherwise,        p.palette = defaultColors;
    end
    % Backward compatibility: legacy code expected `colors`
    p.colors = p.palette;

    % Inches conversions  (1 inch = 25.4 mm)
    p.col1in   = p.col1mm   / 25.4;
    p.col2in   = p.col2mm   / 25.4;
    p.col1h_in = p.col1h_mm / 25.4;
    p.col2h_in = p.col2h_mm / 25.4;
    if isfield(p, 'col15mm') && isfinite(p.col15mm)
        p.col15in   = p.col15mm   / 25.4;
        p.col15h_in = p.col15h_mm / 25.4;
    else
        p.col15mm   = NaN;  p.col15h_mm = NaN;
        p.col15in   = NaN;  p.col15h_in = NaN;
    end
end


function s = mergeWithDefaults(userStruct)
% Fill in missing fields with sensible defaults so user can pass a partial struct.
    defaults.name           = 'Custom';
    defaults.full           = 'Custom user-defined preset';
    defaults.col1mm         = 88.9;
    defaults.col1h_mm       = 65.0;
    defaults.col2mm         = 181.0;
    defaults.col2h_mm       = 90.0;
    defaults.col15mm        = NaN;
    defaults.col15h_mm      = NaN;
    defaults.maxHmm         = 230.0;
    defaults.font           = 'Arial';
    defaults.fontFallback   = {'Arial','Helvetica','sans-serif'};
    defaults.bodyPt         = 8;
    defaults.axisPt         = 8;
    defaults.legendPt       = 7;
    defaults.titlePt        = 10;
    defaults.strokePt       = 0.75;
    defaults.axesPt         = 0.6;
    defaults.gridPt         = 0.3;
    defaults.paletteName    = 'wong';
    defaults.colorblindSafe = true;
    defaults.bg             = '#ffffff';
    defaults.axisColor      = '#000000';
    defaults.gridColor      = '#DDDDDD';
    defaults.formats        = {'PDF','EPS','PNG','TIFF'};
    defaults.dpi            = 300;
    defaults.interpreter    = 'tex';
    defaults.notes          = 'User-defined custom preset';

    s = defaults;
    fns = fieldnames(userStruct);
    for i = 1:numel(fns)
        s.(fns{i}) = userStruct.(fns{i});
    end
end


function s = makePreset(name, fullName, ...
        col1mm, col1h_mm, col2mm, col2h_mm, col15mm, col15h_mm, maxHmm, ...
        font, fontFallback, ...
        bodyPt, axisPt, legendPt, titlePt, ...
        strokePt, axesPt, gridPt, ...
        paletteName, colorblindSafe, bg, axisColor, gridColor, ...
        formats, dpi, interpreter, notes)
    s.name           = name;
    s.full           = fullName;
    s.col1mm         = col1mm;
    s.col1h_mm       = col1h_mm;
    s.col2mm         = col2mm;
    s.col2h_mm       = col2h_mm;
    s.col15mm        = col15mm;
    s.col15h_mm      = col15h_mm;
    s.maxHmm         = maxHmm;
    s.font           = font;
    s.fontFallback   = fontFallback;
    s.bodyPt         = bodyPt;
    s.axisPt         = axisPt;
    s.legendPt       = legendPt;
    s.titlePt        = titlePt;
    s.strokePt       = strokePt;
    s.axesPt         = axesPt;
    s.gridPt         = gridPt;
    s.paletteName    = paletteName;
    s.colorblindSafe = colorblindSafe;
    s.bg             = bg;
    s.axisColor      = axisColor;
    s.gridColor      = gridColor;
    s.formats        = formats;
    s.dpi            = dpi;
    s.interpreter    = interpreter;
    s.notes          = notes;
end
